General:
    MODEL_NAME: DeepAttn_MIL
    seed: 2024
    num_classes: 2
    num_epochs: 100
    device: 0
    num_workers: 4
    best_model_metric: macro_auc  
    earlystop: 
        use: False
        patience: 15
        metric: macro_auc

Dataset:
    DATASET_NAME: STANFORD
    # when used a single csv file
    dataset_csv_path: None
    # when used multiple folds in a folder
    dataset_root_dir: None
    # feature extractor used
    feature_extractor: resnet50_1024
    
    balanced_sampler:
        use: False
        replacement: True

Logs:
    log_root_dir: logs/CLAM

Model:
    in_dim: 1024
    embedding_dim: 64
    attention_dim: 32
    fc_dim: 32
    cluster_num: 10
    dropout: 0.5
    act: relu
    l1_lambda: 0.00001
    
    optimizer:
        which: adam
        adam_config:
            lr: 0.0001
            weight_decay: 0.0005
        adamw_config:
            lr: 0.0001
            weight_decay: 0.0005
    
    criterion: ce  
    
    scheduler:
        warmup: 5
        which: step  # Change from 'plateau' to 'step'
        step_config:
            step_size: 30
            gamma: 0.5
        multi_step_config:
            milestones: [30, 60, 90]
            gamma: 0.5
        exponential_config:
            gamma: 0.95
        cosine_config:
            T_max: 50
            eta_min: 0.000001